### ISSUE TITLE
Parsing crashed on GD file from Breseq 0.26.1

### ISSUE THREAD

**Issue by pvphaneuf** [biosustain/genomediff-python#2]
I've just testing genomediff parsing on a GD file that was created using Breseq 0.26.1.

I've executed genomediff on a GD file that we're currently parsing and received the following error:

Python 3.4.0 (default, Jun 19 2015, 14:20:21) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from genomediff import *
>>> document = GenomeDiff.read(open('2-1.gd', 'r', encoding='utf-8'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/genomediff/__init__.py", line 19, in read
    for record in GenomeDiffParser(document=gd, fsock=fsock):
  File "/usr/local/lib/python3.4/dist-packages/genomediff/parser.py", line 85, in __iter__
    raise Exception('Could not parse line #{}: {}'.format(i, line))
Exception: Could not parse line #12: RA	6	.	NC_000913	4541	0	A	T	bias_e_value=64.2575	bias_p_value=1.38437e-05	fisher_strand_p_value=9.29839e-07	frequency=2.083e-01	genotype_quality=260.6	ks_quality_p_value=1	log10_base_likelihood=-17.0334	log10_qual_likelihood_position_model=19.0126	log10_strand_likelihood_position_model=6.23447	new_cov=20/0	polymorphism_quality=11.7	quality=11.7	quality_position_model=Inf	ref_cov=32/44	reject=POLYMORPHISM_STRAND,FISHER_STRAND_P_VALUE	tot_cov=52/44

This data was generated from FASTQs from the CfB; I'll email you the data shortly.

**Comment by lyschoening** [comment]
Hi Patric,

I didn't get a file with your email? 

The issue was the '.' for the missing parent ids. We tested with files that had a blank field instead. I released 0.2.1 with a fix. Let me know if you encounter more issues. If you send me a file I will make sure that it works.
