### ISSUE TITLE
Pull request #4 and continuing maintenance

### ISSUE THREAD

**Issue by jeffreybarrick** [biosustain/genomediff-python#5]
Hello! Thanks for creating this GenomeDiff parser.

Are you still maintaining this package? I noticed that this pull request (#4) is needed to fix some indentation that prevents objects from printing as strings as shown in the example usage.

If you are not planning any updates, would you consider transferring maintenance to myself and the main team of _breseq_ developers? We like the idea of having an officially supported Python module for working with GenomeDiff files.

**Comment by meono** [comment]
Hi Jeffrey,

No, we aren't maintaining this package any longer. It's great that you want to take over. I think our director already registered you for this repo. If you need anything else, please let us know.

**Comment by jeffreybarrick** [comment]
Great! 

Can you also add me as a maintainer for the python package here?
https://pypi.org/project/genomediff/

My username for PyPI is jbarrick

**Comment by lyschoening** [comment]
Hi @jeffreybarrick, I've added you on PyPI. Feel free to reach out to me if there is anything more. Please @-mention me though - otherwise I won't get the message :)

Best,
Lars

**Comment by jeffreybarrick** [comment]
Thanks for the quick response!
